name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        cd myexpressapp
        docker build . -t vickybytes.azurecr.io/myexpressapp:${{ github.sha }}
  
    - uses: Azure/container-scan@v0
      with:
        image-name: vickybytes.azurecr.io/myapp:${{ github.sha }}
